### ISSUE TITLE
Objects not being created

### ISSUE THREAD

**Issue by arfni** [samp-incognito/samp-streamer-plugin#175]
Using v2.8.2: https://puu.sh/uYODu/91f8ec0bad.png
Using v2.9.0: https://puu.sh/uYNUT/a96bad890a.png

Possibly relevant info:
Outside of the normal map , a lot of objects / text labels & areas.

**Comment by samp-incognito** [comment]
Interesting. Possibly related to #174?

Have the objects not been created (check with Streamer_GetVisibleItems) or are they just not visible for some reason? It looks like the car is sitting on an object there.

**Comment by arfni** [comment]
The object below the car is created with CreateObject.

Streamer_GetVisibleItems(STREAMER_TYPE_OBJECT) returns 500, but the objects are "physically" not there.

**Comment by samp-incognito** [comment]
There must be some objects somewhere then. Are you not seeing any objects anywhere, or are they just not being created at that specific location?

**Comment by arfni** [comment]
Theres nothing, not even the text labels are there.

Interestingly enough, objects that were created before I connected are working just fine.

**Comment by samp-incognito** [comment]
As with the other issue:

> See if [samp-streamer-plugin-2.9.0-test.zip](https://github.com/samp-incognito/samp-streamer-plugin/releases/download/v2.9.0/samp-streamer-plugin-2.9.0-test.zip) fixes this.

I couldn't reproduce this specifically, but it might be related to some of the other bugs I just fixed.

**Comment by arfni** [comment]
Still the same issue.

When pressing F5 it says that there are ~ 230-240 objects somewhere in the world ( I have not created a single static object. )
https://puu.sh/uZKWM/279236b277.png

**Comment by samp-incognito** [comment]
Can you reproduce it in an empty script?

Everything seems to work fine for me. Maybe it's some native or callback your script is using that's now bugged in this version. If that's the case, and you can find out what's triggering it, it would be helpful.

**Comment by arfni** [comment]
Did it in an empty script, still does not work.

These are all natives that I use:
CreateDynamicObjectEx
Streamer_SetIntData
SetDynamicObjectMaterial (Just in some cases | very rarely)

**Comment by samp-incognito** [comment]
So CreateDynamicObject is working for you but CreateDynamicObjectEx is noy

**Comment by arfni** [comment]
CreateDynamicObjectEx(8558, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 300.0, 300.0, VirtualWorlds[gamemodeid]);

gamemodeid -> int between 0 and 9
VirtualWorlds -> static 2 dimensional array [9][65]
Index 0 -> 0-64 
Index 1 -> 100-164
And so on. 
( written in my phone... )

**Comment by samp-incognito** [comment]
Possibly related to virtual worlds then? See if CreateDynamicObjectEx works with the virtual world set to just -1.

**Comment by arfni** [comment]
Doesn't work with -1.

**Comment by samp-incognito** [comment]
I'm at a loss then if no errors are being outputted to the server log. There's really no reason why CreateDynamicObjectEx shouldn't be working here. It's working fine for me, so I'll wait to see if anyone else is having this problem, I guess.

**Comment by arfni** [comment]
https://www.dropbox.com/s/tv8znszkw5box5q/streamer.test.zip?dl=0
(For some reason I can't upload .zip files.. https://puu.sh/v2iAg/1c6d5a5ebd.png)

**Comment by samp-incognito** [comment]
Thanks, that was very helpful.

I did find a small bug which I think was causing this, though I'm not sure why it was only occurring under those circumstances. See if [samp-streamer-plugin-2.9.0-test-2.zip](https://github.com/samp-incognito/samp-streamer-plugin/releases/download/v2.9.0/samp-streamer-plugin-2.9.0-test-2.zip) fixes this.

**Comment by arfni** [comment]
Works, thanks :)

**Comment by samp-incognito** [comment]
Good, thanks for reporting.
